load("@org_pubref_rules_protobuf//go:rules.bzl", "go_proto_library")

go_proto_library(
    name = "go_default_library",
    protos = [
        "prometheus.proto",
    ],
    verbose = 0,
    visibility = ["//adapter/prometheus:__pkg__"],
)
